name: shop_firbase_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  fluttertoast: ^8.1.1
  carousel_slider: ^4.1.1
  file_picker: ^5.0.1
  image_picker: ^0.8.5+3
  email_validator: '^2.1.16'
  flutter_svg: ^1.1.1+1
  lottie: ^1.4.3
  modal_bottom_sheet: ^2.0.1
  easy_localization: ^3.0.1
  flutter_linkify: ^5.0.2
  intl: ^0.17.0
  zoom_tap_animation: ^1.1.0
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.5.4
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0
  telephony: ^0.2.0
  url_launcher: ^6.1.11

  #Firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0
  firebase_analytics: ^10.0.6
  firebase_in_app_messaging: ^0.7.0+7
  firebase_messaging: ^14.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

